### ISSUE TITLE
CantactPRO CLI does not install on Ubuntu 

### ISSUE THREAD

**Issue by CarWrestler** [linklayer/cantact#7]
Tried installing Cantact PRO CLI as mentioned at https://contact.io, got the following errors (see screenshots)  

below is the version info: 
testuser@testLat7480:~$ cat /etc/os-release | grep VERSION
VERSION="20.04.1 LTS (Focal Fossa)"
VERSION_ID="20.04"
VERSION_CODENAME=focal
![Cantact1Error](https://user-images.githubusercontent.com/75737905/101646036-08b10b00-3a05-11eb-95e8-ebc865a92ac7.png)
![Cantact2Error](https://user-images.githubusercontent.com/75737905/101646071-1070af80-3a05-11eb-97ea-0a93383243bf.png)
![Cantact3Error](https://user-images.githubusercontent.com/75737905/101646103-18305400-3a05-11eb-91b2-b340d9880bfa.png)

**Comment by ericevenchick** [comment]
Thanks for the report! This was caused by a beta version of the clap CLI library changing the API. I've specified the correct version of this library now, and the build is working again.
