### ISSUE TITLE
Device not found

### ISSUE THREAD

**Issue by brainstorm** [linklayer/cantact#8]
@ericevenchick This is a followup on issue #3 , I'm not finding my cantact device with the python interface either: 

```
$ pip install cantact

(...all ok...)

$ ipython
Python 3.7.9 | packaged by conda-forge | (default, Dec  9 2020, 20:58:55) 
Type "copyright", "credits" or "license" for more information.

IPython 5.8.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import cantact

In [2]: foo = cantact.Interface()
---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
<ipython-input-2-c321422b385c> in <module>()
----> 1 foo = cantact.Interface()

SystemError: DeviceNotFound
```

As mentioned on issue #3 , I'm testing cantact in a STM32F042G6 board since I bought the cantact-pro and I'd like to be familiar when it arrives. 

Happy to debug/test it further for you, hints on what might be going on appreciated though ;)

**Comment by ericevenchick** [comment]
Hmm, from #3 it looks like the wrong PID/VID... there have been a few out there. Can you confirm the PID/VID here using lsusb?

**Comment by brainstorm** [comment]
Fixed by using candlelight-cantact_fw instead of the "old" serial/ACM firmware in https://github.com/linklayer/cantact/issues/3#issuecomment-748440414, closing
